name: Move card

on:

  issues:
    types: [assigned]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ineshbose/project-card-action@v1
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          TARGET_COLUMN: 'Todo'