# This pipeline automatically adds reviewers to the pull request.

name: Add Reviewers

on:
  pull_request:
    types: [opened, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Add Reviewers
      uses: madrapps/add-reviewers@v1
      with:
        token: ${{ secrets.GH_TOKEN }}
        reviewers: "algertislamaj"
        re-request-when-approved: true
        re-request-when-changes-requested: true
