name: Issue Assigned Workflow

on:
  issues:
    types: [assigned]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to project board
        uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: Backstage-IDP
          column: Iteration 1 (30 Jan - 13 Feb 2024)
          repo-token: ${{ secrets.GH_TOKEN }}
