name: Assign issues

on:
  issues:
    types: [assigned]

jobs:
  assign:
    name: Assign issues to project
    runs-on: ubuntu-latest
    steps:
      - name: Assign issues to project
        uses: technote-space/create-project-card-action@v1
        with:
          PROJECT: Test
          COLUMN: To do
