name: Move assigned issues to Todo field

on:
  issues:
    types: [assigned]

jobs:
  update-status:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Update status to "In Review"
        uses: nipe0324/update-project-v2-item-field@v2.0.1
        with:
          project-url: https://github.com/users/algertislamaj/projects/1
          github-token: ${{ secrets.GH_TOKEN }}
          field-name: "Status"
          field-value: "Todo"
