name: Move assigned issues to Todo column

on:
  issues:
    types: [assigned]

jobs:
  move-issue-to-todo-column:
    name: Move issues to Todo column
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to 'Todo' column
        uses: fojia/action-move-issues-to-column@master
        with:
          project: "Test"
          column: 'Todo'
          owner: 'algertislamaj'
          repo: 'test2'
          type: 'repo'
          github_token: ${{ secrets.GH_TOKEN }}
