# This pipeline moves issues between fields based on how they change.
# If the issue is assigned to someone the pipeline moves issues to the field "Todo". 
# If the issue is closed, it moves it to the field "Done". 
# If the issue is reopened, it moves it to the field "In Progress". 

name: Move issues between fields

on:
  issues:
    types: [assigned, closed, reopened]

jobs:
  update-status:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Update status to "Todo"
        if: github.event.action == 'assigned'
        uses: nipe0324/update-project-v2-item-field@v2.0.1
        with:
          project-url: ${{ secrets.PROJECT_URL }}
          github-token: ${{ secrets.GH_TOKEN }}
          field-name: "Status"
          field-value: "Todo"
      - name: Update status to "Done"
        if: github.event.action == 'closed'
        uses: nipe0324/update-project-v2-item-field@v2.0.1
        with:
          project-url: ${{ secrets.PROJECT_URL }}
          github-token: ${{ secrets.GH_TOKEN }}
          field-name: "Status"
          field-value: "Done"
      - name: Update status to "In Progress"
        if: github.event.action == 'reopened'
        uses: nipe0324/update-project-v2-item-field@v2.0.1
        with:
          project-url: ${{ secrets.PROJECT_URL }}
          github-token: ${{ secrets.GH_TOKEN }}
          field-name: "Status"
          field-value: "In Progress"
